# Generated by Django 4.2.4 on 2023-08-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_product_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
