# Generated by Django 4.2.4 on 2023-09-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
