# Generated by Django 4.2.4 on 2023-09-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_order_user_order_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='shipping',
        ),
    ]
